# lib\tests\test_exceptions.py

from lib.src.engine.exceptions import NoDeckPresent
from lib.src.engine.deck import Deck


# def print_deck():           --- The following function successfully triggers a NoDeckPresent exception 9.23.24
#     #create deck instance
#     deck = Deck()
#     deck.create_deck()

#     #print card names
#     for card in deck.cards:
#         print(card.name)

#     print(f"Total cards in the deck: {len(deck.cards)}")

#     deck.delete_deck()

#     deck.delete_deck()
    

if __name__ == "__main__":
    pass
